# Generated by Django 3.2.9 on 2022-06-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_equipmentcount'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='equipments',
            field=models.ManyToManyField(related_name='all_equipments', through='workouts.WorkoutEquipment', to='equipments.Equipment'),
        ),
        migrations.AlterField(
            model_name='workoutequipment',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Amount'),
        ),
    ]
