# Generated by Django 3.2.9 on 2022-06-17 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='equipments',
        ),
    ]
