# Generated by Django 3.2.9 on 2022-06-18 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_auto_20220618_2139'),
        ('workouts', '0002_auto_20220618_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutequipment',
            name='equipment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_equipments', to='equipments.equipment'),
        ),
    ]
