# Generated by Django 3.2.9 on 2022-06-18 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_auto_20220618_2139'),
        ('workouts', '0004_alter_workoutequipment_equipment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workoutequipment',
            unique_together={('equipment', 'workout')},
        ),
    ]
