# Generated by Django 3.2.9 on 2022-06-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_alter_workoutequipment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutequipment',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Amount'),
        ),
    ]
