# Generated by Django 3.2.9 on 2022-06-18 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCount',
            fields=[
                ('mastermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.mastermodel')),
                ('amount', models.IntegerField(default=1, verbose_name='Amount')),
                ('my_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_counts', to='equipments.equipment')),
            ],
            bases=('base.mastermodel',),
        ),
    ]
