# Generated by Django 3.2.9 on 2022-06-18 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_equipmentcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentcount',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='equipmentcount',
            name='my_equipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_counts', to='equipments.equipment'),
        ),
    ]
