# Generated by Django 3.2.9 on 2022-06-17 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_remove_workout_equipments'),
        ('equipments', '0002_equipment_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.workout'),
        ),
    ]
